
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-5pm-3
owner: ucsb-cs156-w24
repo_name: team01-w24-5pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ4MTI4MDUw","is_bot":false,"login":"bigjr-mkkong","name":"michael"},"headRefName":"Michael-LocationQueryServices","number":35,"title":"Update Controller description","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-3/pull/35"},{"author":{"id":"U_kgDOBdYtJA","is_bot":false,"login":"bwr02","name":"Ben Richardson"},"headRefName":"Animesh-Bug-Fixes","number":34,"title":"Joke and Locations fixed controller output. Fixed Joke service ","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-3/pull/34"}]
