
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-5pm-3
owner: ucsb-cs156-w24
repo_name: team01-w24-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBdYtJA","is_bot":false,"login":"bwr02","name":"Ben Richardson"},"headRefName":"Ben-Tides-Controller","number":29,"title":"Ben tides controller and controller tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-3/pull/29"},{"author":{"id":"U_kgDOBdHtDQ","is_bot":false,"login":"Shakcmpsc","name":""},"headRefName":"Yerassyl-Joke-Controller","number":28,"title":"Add joke controller ","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-3/pull/28"},{"author":{"id":"U_kgDOBdHtDQ","is_bot":false,"login":"Shakcmpsc","name":""},"headRefName":"Yerassyl-Joke","number":27,"title":"Add Joke Service","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-3/pull/27"},{"author":{"id":"U_kgDOBdHK8A","is_bot":false,"login":"chloeqta","name":""},"headRefName":"Chloe-HomeController","number":26,"title":"Customized HomeController and tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-3/pull/26"},{"author":{"id":"U_kgDOBXv56g","is_bot":false,"login":"sophiattran","name":""},"headRefName":"Sophia-University-Controller","number":24,"title":"Add University Controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-3/pull/24"},{"author":{"id":"MDQ6VXNlcjc5MzcxNjc1","is_bot":false,"login":"theanimated01","name":"Animesh Sachan"},"headRefName":"Animesh-ZipCode-Controller","number":22,"title":"Add ZipCode Service and Controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-3/pull/22"},{"author":{"id":"U_kgDOBdYtJA","is_bot":false,"login":"bwr02","name":"Ben Richardson"},"headRefName":"Ben-Tides","number":21,"title":"Ben tides Service and Service tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-3/pull/21"},{"author":{"id":"U_kgDOBdHK8A","is_bot":false,"login":"chloeqta","name":""},"headRefName":"Chloe-PublicHoliday-Controller","number":19,"title":"Add PublicHoliday Controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-3/pull/19"}]
